// Original exercise guidance and movement previews for Lift Log.
// Variants stay in the same movement family; machine loads are not carried across variants.
window.LIFT_EXERCISE_DATA = {
  patterns: {
    inclinePress: {gif:'incline-press.gif', setup:'Set the bench to a low incline. Keep your feet planted and shoulder blades gently pulled back.', move:'Lower with control toward your upper chest, then press up without bouncing.', avoid:'Do not flare your elbows straight out or lift your hips off the bench.', options:[['Incline Barbell Bench Press','barbell'],['Incline Dumbbell Press','dumbbell'],['Incline Machine Press','machine'],['Incline Smith Machine Press','machine'],['Single-Arm Incline Dumbbell Press','dumbbell'],['Incline Push-Up','bodyweight'],['Feet-Elevated Push-Up','bodyweight'],['Incline Cable Press','cable'],['Incline Band Press','band']]},
    chestPress: {gif:'chest-press.gif', setup:'Set handles near mid-chest, keep feet planted and shoulders down.', move:'Press forward smoothly and return until you feel a comfortable chest stretch.', avoid:'Do not shrug or let the shoulders roll far forward.', options:[['Machine Chest Press','machine'],['Flat Dumbbell Press','dumbbell'],['Flat Barbell Bench Press','barbell'],['Smith Machine Bench Press','machine'],['Cable Chest Press','cable'],['Push-Up','bodyweight'],['Band Chest Press','band'],['Single-Arm Machine Press','machine']]},
    row: {gif:'row.gif', setup:'Support your chest or brace your torso. Let your shoulder blades reach forward at the start.', move:'Pull your elbows back toward your hips, pause briefly, then lower under control.', avoid:'Do not swing your torso to move the weight.', options:[['Chest-Supported T-Bar Row','machine'],['Chest-Supported Row','machine'],['Chest-Supported Dumbbell Row','dumbbell'],['Seated Cable Row','cable'],['One-Arm Dumbbell Row','dumbbell'],['Barbell Row','barbell'],['Inverted Row','bodyweight'],['Band Row','band'],['Single-Arm Machine Row','machine']]},
    verticalPull: {gif:'vertical-pull.gif', setup:'Sit tall and secure your thighs. Grip the handles with arms fully reaching overhead.', move:'Pull elbows toward your ribs and bring the handles toward upper chest; return slowly.', avoid:'Do not yank with your lower back or pull behind your neck.', options:[['Neutral-Grip Lat Pulldown','machine'],['Wide-Grip Lat Pulldown','machine'],['Close-Grip Lat Pulldown','machine'],['Single-Arm Cable Pulldown','cable'],['Assisted Pull-Up','machine'],['Pull-Up','bodyweight'],['Band-Assisted Pull-Up','band'],['Kneeling Band Pulldown','band'],['Chin-Up','bodyweight']]},
    fly: {gif:'fly.gif', setup:'Stand with one foot slightly forward and elbows softly bent.', move:'Bring your hands together in an arc, then open slowly until you feel a comfortable chest stretch.', avoid:'Do not turn this into a press or pull your arms too far behind your body.', options:[['Low-to-High Cable Fly','cable'],['Single-Arm Low-to-High Cable Fly','cable'],['Pec Deck Fly','machine'],['Cable Chest Fly','cable'],['Incline Dumbbell Fly','dumbbell'],['Flat Dumbbell Fly','dumbbell'],['Band Chest Fly','band'],['Wide Push-Up','bodyweight'],['Machine Fly','machine']]},
    lateralRaise: {gif:'lateral-raise.gif', setup:'Stand tall, elbows softly bent and shoulders relaxed.', move:'Raise your arms out to the sides to about shoulder height, then lower slowly.', avoid:'Do not shrug or swing your torso.', options:[['Cable Lateral Raise','cable'],['Dumbbell Lateral Raise','dumbbell'],['Machine Lateral Raise','machine'],['Behind-the-Body Cable Lateral Raise','cable'],['Leaning Cable Lateral Raise','cable'],['Single-Arm Dumbbell Lateral Raise','dumbbell'],['Band Lateral Raise','band'],['Seated Dumbbell Lateral Raise','dumbbell'],['Lateral Raise Hold','bodyweight']]},
    hipThrust: {gif:'hip-thrust.gif', setup:'Place your upper back on a sturdy bench and feet about hip-width apart.', move:'Drive through your feet and lift your hips until shoulders, hips and knees align.', avoid:'Do not overarch your lower back at the top.', options:[['Hip Thrust','barbell'],['Smith Machine Hip Thrust','machine'],['Dumbbell Hip Thrust','dumbbell'],['Machine Hip Thrust','machine'],['Glute Bridge','bodyweight'],['Single-Leg Glute Bridge','bodyweight'],['Band Glute Bridge','band'],['Barbell Glute Bridge','barbell']]},
    hinge: {gif:'hinge.gif', setup:'Stand tall with soft knees and hold the load close to your legs.', move:'Push hips back until you feel hamstrings stretch, then stand by driving hips forward.', avoid:'Do not round your lower back or squat the weight down.', options:[['Romanian Deadlift','barbell'],['Dumbbell Romanian Deadlift','dumbbell'],['Single-Leg Romanian Deadlift','dumbbell'],['Smith Machine Romanian Deadlift','machine'],['Cable Pull-Through','cable'],['Good Morning','barbell'],['Bodyweight Hip Hinge','bodyweight'],['Band Good Morning','band'],['45-Degree Back Extension','bodyweight']]},
    kneeExtension: {gif:'knee-extension.gif', setup:'Set the machine axis near your knee and position the pad above your ankles.', move:'Straighten your knees smoothly, pause, then lower without dropping the weight.', avoid:'Do not force a painful range or lift your hips from the seat.', options:[['Leg Extension','machine'],['Single-Leg Extension','machine'],['Spanish Squat','band'],['Goblet Squat','dumbbell'],['Heel-Elevated Squat','bodyweight'],['Step-Up','bodyweight'],['Split Squat','bodyweight'],['Hack Squat Machine','machine'],['Barbell Front Squat','barbell']]},
    legCurl: {gif:'leg-curl.gif', setup:'Align the machine pivot with your knee and set the pad near your lower leg.', move:'Curl your heels toward your hips, pause, then lower slowly.', avoid:'Do not arch your back or swing the weight.', options:[['Seated Leg Curl','machine'],['Lying Leg Curl','machine'],['Standing Single-Leg Curl','machine'],['Sliding Hamstring Curl','bodyweight'],['Stability-Ball Hamstring Curl','bodyweight'],['Band Leg Curl','band'],['Nordic Curl','bodyweight'],['Cable Leg Curl','cable']]},
    calfRaise: {gif:'calf-raise.gif', setup:'Place the balls of your feet on the platform and keep your knees gently unlocked.', move:'Lower your heels to a comfortable stretch and rise fully onto your toes.', avoid:'Do not bounce at the bottom.', options:[['Standing Calf Raise','machine'],['Seated Calf Raise','machine'],['Leg Press Calf Raise','machine'],['Single-Leg Calf Raise','bodyweight'],['Dumbbell Standing Calf Raise','dumbbell'],['Barbell Calf Raise','barbell'],['Smith Machine Calf Raise','machine'],['Band Calf Raise','band']]},
    crunch: {gif:'crunch.gif', setup:'Brace lightly and keep hips still. Start with ribs stacked over your pelvis.', move:'Curl your ribs toward your pelvis, pause, then return slowly.', avoid:'Do not pull with your arms or swing your hips.', options:[['Cable Crunch','cable'],['Ab Crunch Machine','machine'],['Floor Crunch','bodyweight'],['Reverse Crunch','bodyweight'],['Band Crunch','band'],['Decline Crunch','bodyweight'],['Weighted Crunch','dumbbell'],['Kneeling Cable Crunch','cable']]},
    rearDelt: {gif:'rear-delt.gif', setup:'Keep your chest supported or hinge at the hips, with arms in front of you.', move:'Open your arms out and slightly back, then return slowly.', avoid:'Do not shrug or throw the weight with your torso.', options:[['Reverse Pec Deck','machine'],['Rear Delt Fly Machine','machine'],['Cable Rear-Delt Fly','cable'],['Dumbbell Rear-Delt Raise','dumbbell'],['Chest-Supported Rear-Delt Raise','dumbbell'],['Band Pull-Apart','band'],['Face Pull','cable'],['Prone Y-Raise','bodyweight']]},
    curl: {gif:'curl.gif', setup:'Keep elbows near your sides and wrists straight.', move:'Bend your elbows to raise the load, then lower it fully with control.', avoid:'Do not swing your shoulders or lean back.', options:[['Preacher Curl','machine'],['Bayesian Cable Curl','cable'],['Cable Curl','cable'],['Hammer Curl','dumbbell'],['Incline Dumbbell Curl','dumbbell'],['EZ-Bar Curl','barbell'],['Band Curl','band'],['Chin-Up','bodyweight'],['Concentration Curl','dumbbell'],['Machine Curl','machine']]},
    triceps: {gif:'triceps.gif', setup:'Keep upper arms still and shoulders relaxed.', move:'Straighten your elbows against resistance, then return slowly.', avoid:'Do not swing your torso or let elbows flare widely.', options:[['Single-Arm Cable Triceps Extension','cable'],['Rope Pushdown','cable'],['Single-Arm Cable Pushdown','cable'],['Overhead Cable Extension','cable'],['Dumbbell Overhead Extension','dumbbell'],['Machine Triceps Extension','machine'],['Close-Grip Push-Up','bodyweight'],['Band Pushdown','band'],['Close-Grip Bench Press','barbell']]},
    legRaise: {gif:'leg-raise.gif', setup:'Hang securely with shoulders engaged and ribs down.', move:'Lift knees or legs by curling your pelvis upward, then lower without swinging.', avoid:'Do not kick or use momentum.', options:[['Weighted Hanging Leg Raise','bodyweight'],['Hanging Knee Raise','bodyweight'],['Captain’s-Chair Knee Raise','machine'],['Lying Leg Raise','bodyweight'],['Reverse Crunch','bodyweight'],['Incline Bench Leg Raise','bodyweight'],['Cable Reverse Crunch','cable'],['Dead Bug','bodyweight']]},
    pullover: {gif:'pullover.gif', setup:'Keep ribs down and elbows softly bent.', move:'Move your arms through a comfortable overhead arc, then pull toward your torso.', avoid:'Do not force your shoulders past a comfortable range.', options:[['Straight-Arm Pulldown','cable'],['Dumbbell Pullover','dumbbell'],['Cable Pullover','cable'],['Machine Pullover','machine'],['Kneeling Straight-Arm Pulldown','cable'],['Band Straight-Arm Pulldown','band'],['Single-Arm Cable Pullover','cable'],['Floor Dumbbell Pullover','dumbbell']]},
    dip: {gif:'dip.gif', setup:'Support yourself on stable bars with shoulders down.', move:'Bend elbows to a comfortable depth, then press back up.', avoid:'Do not drop into a deep range that causes shoulder pain.', options:[['Weighted Dips','bodyweight'],['Assisted Dips','machine'],['Bodyweight Dips','bodyweight'],['Close-Grip Push-Up','bodyweight'],['Machine Dip','machine'],['Close-Grip Bench Press','barbell'],['Cable Chest Press','cable'],['Dumbbell Floor Press','dumbbell']]}
  },
  byId: {
    'incline-barbell':'inclinePress','tbar-row':'row','machine-press':'chestPress','low-high-fly':'fly','cable-lateral':'lateralRaise',
    'hip-thrust':'hipThrust','rdl':'hinge','leg-extension':'kneeExtension','seated-curl':'legCurl','calf-raise':'calfRaise','cable-crunch':'crunch',
    'reverse-pec':'rearDelt','preacher':'curl','single-triceps':'triceps','db-lateral':'lateralRaise','bayesian-curl':'curl',
    'incline-db':'inclinePress','neutral-pulldown':'verticalPull','chest-row':'row','pec-deck':'fly','rear-delt':'rearDelt','hanging-raise':'legRaise',
    'straight-pulldown':'pullover','cable-curl':'curl','rope-pushdown':'triceps','machine-lateral':'lateralRaise','ab-crunch':'crunch',
    'dips':'dip','pullover':'pullover','behind-lateral':'lateralRaise','hammer-curl':'curl'
  },
  equipmentLabels: {barbell:'Barbells',dumbbell:'Dumbbells',machine:'Machines',cable:'Cables',bodyweight:'Bodyweight',band:'Bands'}
};
